### ISSUE TITLE
DemonRC Flow

### ISSUE THREAD

**Issue by dweight** [theely/Open-GoPro-Mount#3]
Hi, I've created a 30deg GoPro Hero 5/6/7 mount for DRC Flow and would like to get access to the repo in order to publish it :)

**Comment by theely** [comment]
With pleasure!
Feel free to open a pull request. If you need help just drop a comment here.

**Comment by dweight** [comment]
It looks like I need a write access  in order to push my changes and open PR. Would you mind adding me (dweight) to the allowed list?

**Comment by theely** [comment]
Pull requests should be open to everyone.
First you need to create a fork of the project, then you make the changes on your fork and only then you should be able to marge your changes with a PR.

Or is there a simpler way?

**Comment by theely** [comment]
From GitHub doc: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by dweight** [comment]
Thanks for the tip :) I'll try it that way.
