### ISSUE TITLE
Improve Screen Protection fitting

### ISSUE THREAD

**Issue by theely** [theely/Open-GoPro-Mount#5]
Fitting the screen protection is quite challenging due to the very small tolerances.

Are the lateral supports required or even without them the screen protection is well anchored to the GoPro holder?
![97083173-b2cc0380-160e-11eb-84cd-b8f02e43585c](https://user-images.githubusercontent.com/2025999/97085750-a43a1800-161f-11eb-8d8a-70ffb6b5566c.png)

New simplified version:
![Screenshot 2020-10-24 at 17 47 08](https://user-images.githubusercontent.com/2025999/97085967-f4fe4080-1620-11eb-8045-e3fb8bb6673d.png)

[GoPro Screen Protection v24.stl.zip](https://github.com/theely/Open-GoPro-Mount/files/5433125/GoPro.Screen.Protection.v24.stl.zip)

**Comment by dweight** [comment]
Hi! I've printed and tested the fitting - fits firm into the mount.

**Comment by theely** [comment]
Great, going to close this issue! I have updated the STEP and STL files
