### ISSUE TITLE
HyperLow Frame Support

### ISSUE THREAD

**Issue by QingwenWei** [theely/Open-GoPro-Mount#6]
Support for all hyper low frames just requires a 30x30 mm mounting pattern.

**Comment by theely** [comment]
This should be straightforward, I'll add it.

**Comment by theely** [comment]
Could you please test this first prototype and let me know if it fits well?
[HyperLow GoPro Hero 8 Mount 22° v4.stl.zip](https://github.com/theely/Open-GoPro-Mount/files/5515495/HyperLow.GoPro.Hero.8.Mount.22.v4.stl.zip)

**Comment by QingwenWei** [comment]
I printed just the base to test. There is some misalignment.
Sorry for not really going into detail on the mounting pattern. It's a 30.5 x 30.5 mm pattern like that of a 30x30 flight controller. So a square of 30.5x30.5 mm with holes in each corner. The front holes are too narrow and the rest probably should get the extra .5 mm distance to get the perfect fit.

**Comment by theely** [comment]
No problem! Could you please send me a photo? It helps to understand how to further improve the mount.

**Comment by QingwenWei** [comment]
Yeah sure.
![20201110_190711083_iOS](https://user-images.githubusercontent.com/45522704/98721479-d907d800-235e-11eb-9b83-b6c790fb7439.jpg)
![20201110_191022245_iOS](https://user-images.githubusercontent.com/45522704/98721827-f2108900-235e-11eb-9da0-f2980ebf4490.jpg)
![20201110_190803085_iOS](https://user-images.githubusercontent.com/45522704/98721526-dc9b5f00-235e-11eb-81d5-d2b342afa156.jpg)
![20201110_190823861_iOS](https://user-images.githubusercontent.com/45522704/98721574-df964f80-235e-11eb-8868-53521ecfbdf3.jpg)
![20201110_190836869_iOS](https://user-images.githubusercontent.com/45522704/98721637-e329d680-235e-11eb-8cb4-3df6b355db3c.jpg)
![20201110_190929823_iOS](https://user-images.githubusercontent.com/45522704/98721679-e6bd5d80-235e-11eb-94fc-4c293524e5f2.jpg)
![20201110_190948686_iOS](https://user-images.githubusercontent.com/45522704/98721729-ea50e480-235e-11eb-8171-4617e34dfbb5.jpg)
![20201110_190959679_iOS](https://user-images.githubusercontent.com/45522704/98721766-ede46b80-235e-11eb-8f5b-36332bec772d.jpg)

**Comment by theely** [comment]
Great that was super helpful!
I have fixed a bug on the front mounting holes and extended to 30.5mm.
[HyperLow GoPro Hero 8 Mount 22.5° v5.stl.zip](https://github.com/theely/Open-GoPro-Mount/files/5519899/HyperLow.GoPro.Hero.8.Mount.22.5.v5.stl.zip)

**Comment by QingwenWei** [comment]
Fits perfect now, the only thing is the outside of the front mounting holes is slightly biggger then the frame.
Also could you do it for the hero 7 at 30 degrees. Thank you so much for develpoing this!
![20201110_202754705_iOS](https://user-images.githubusercontent.com/45522704/98729878-841d8f00-2369-11eb-99c2-78044e661189.jpg)

**Comment by theely** [comment]
Ready!
In the STL folder you can find a 30° mount for GoPro Hero 7 and 8.
